# Generated by Django 2.2.24 on 2021-08-18 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0002_category"),
    ]

    operations = [
        migrations.CreateModel(
            name="Restaurant",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("location", models.TextField()),
                ("name", models.CharField(max_length=256)),
                ("user_id", models.IntegerField(blank=True, null=True)),
                ("img_url", models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.DeleteModel(
            name="Category",
        ),
    ]
