# Generated by Django 2.2.24 on 2021-08-18 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0003_auto_20210818_2204"),
    ]

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=1256)),
                ("icon", models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="Deal",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.TextField()),
                ("img_url", models.TextField()),
                ("price", models.IntegerField()),
                ("reduced_price", models.IntegerField()),
                ("restaurant_id", models.IntegerField()),
                ("category_id", models.IntegerField()),
                ("user_id", models.IntegerField()),
                ("special_offer", models.TextField()),
            ],
        ),
    ]
