# Generated by Django 2.2.24 on 2021-08-18 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0004_category_deal"),
    ]

    operations = [
        migrations.CreateModel(
            name="Timeline",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("to", models.TextField(blank=True, null=True)),
                ("weekday", models.TextField(blank=True, null=True)),
            ],
        ),
    ]
