# Generated by Django 2.2.24 on 2021-08-18 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0005_timeline"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="timeline",
            name="to",
        ),
        migrations.AddField(
            model_name="timeline",
            name="time_from",
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="timeline",
            name="time_to",
            field=models.TimeField(blank=True, null=True),
        ),
    ]
