# Generated by Django 2.2.24 on 2021-08-18 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_auto_20210818_2215'),
    ]

    operations = [
        migrations.CreateModel(
            name='Badges',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=1256)),
                ('img_url', models.TextField()),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField()),
                ('created_at', models.DateTimeField()),
                ('action_type', models.CharField(max_length=256)),
                ('action_id', models.IntegerField()),
                ('img_url', models.TextField()),
                ('title', models.TextField()),
                ('description', models.TextField()),
                ('read_status', models.BooleanField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='User_Badge',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField()),
                ('badge_id', models.IntegerField()),
                ('acquired_on', models.DateTimeField(auto_now=True)),
                ('shown', models.BooleanField()),
            ],
        ),
    ]
