# Generated by Django 2.2.24 on 2021-08-31 14:10

from django.conf import settings
import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion
import home.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('home', '0007_badges_notification_user_badge'),
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=255)),
                ('city', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('point', django.contrib.gis.db.models.fields.PointField(srid=4326)),
            ],
        ),
        migrations.RemoveField(
            model_name='deal',
            name='category_id',
        ),
        migrations.RemoveField(
            model_name='deal',
            name='restaurant_id',
        ),
        migrations.RemoveField(
            model_name='deal',
            name='user_id',
        ),
        migrations.RemoveField(
            model_name='notification',
            name='img_url',
        ),
        migrations.RemoveField(
            model_name='notification',
            name='user_id',
        ),
        migrations.RemoveField(
            model_name='restaurant',
            name='user_id',
        ),
        migrations.RemoveField(
            model_name='user_badge',
            name='badge_id',
        ),
        migrations.RemoveField(
            model_name='user_badge',
            name='user_id',
        ),
        migrations.AddField(
            model_name='deal',
            name='category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='home.Category'),
        ),
        migrations.AddField(
            model_name='deal',
            name='restaurant',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='home.Restaurant'),
        ),
        migrations.AddField(
            model_name='deal',
            name='user',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='notification',
            name='user',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='user',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='user_badge',
            name='badge',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to='home.Badges'),
        ),
        migrations.AddField(
            model_name='user_badge',
            name='user',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='badges',
            name='img_url',
            field=models.ImageField(blank=True, null=True, upload_to=home.models.nameFile),
        ),
        migrations.AlterField(
            model_name='deal',
            name='img_url',
            field=models.ImageField(blank=True, null=True, upload_to=home.models.nameFile),
        ),
        migrations.AlterField(
            model_name='deal',
            name='special_offer',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='img_url',
            field=models.ImageField(blank=True, null=True, upload_to=home.models.nameFile),
        ),
    ]
