# Generated by Django 2.2.24 on 2021-09-01 20:35

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0012_auto_20210901_2141'),
    ]

    operations = [
        migrations.CreateModel(
            name='Description',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_type', models.CharField(choices=[('CUSTOMER', 'CUSTOMER'), ('VENDOR', 'VENDOR')], default='VENDOR', max_length=50)),
                ('page_type', models.CharField(choices=[('ABOUT', 'About'), ('TERMS_AND_CONDITIONS', 'Terms and Conditions'), ('PRIVACY_POLICY', 'Privacy Policy')], default='ABOUT', max_length=50)),
                ('header', models.TextField(blank=True, null=True)),
                ('content', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(blank=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
