# Generated by Django 2.2.24 on 2021-10-06 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0018_auto_20211006_0050'),
    ]

    operations = [
        migrations.AddField(
            model_name='deal',
            name='featured',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
