# Generated by Django 2.2.24 on 2022-01-14 16:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0021_user_devicetoken'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Badges',
            new_name='Badge',
        ),
    ]
