# Generated by Django 2.2.25 on 2022-01-16 05:54

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('home', '0023_auto_20220115_0439'),
    ]

    operations = [
        migrations.CreateModel(
            name='PushNoti',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField(blank=True)),
                ('notify_time', models.TimeField(blank=True)),
            ],
        ),
        migrations.RenameModel(
            old_name='Notification',
            new_name='FCMNotification',
        ),
    ]
