# Generated by Django 2.2.25 on 2022-01-16 16:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0024_auto_20220116_1354'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PushNoti',
        ),
    ]
