# Generated by Django 2.2.26 on 2022-01-24 00:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0025_delete_pushnoti'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User_DeviceToken',
        ),
    ]
